server:
  port: 0
spring:
  jackson:
      serialization:
        write-dates-as-timestamps: false
info:
  artifactId: "@project.artifactId@"
  description: "@project.description@"
  version: "@project.version@"