server:
    port: 8081
spring:
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,heapdump,hystrix.stream,turbine.stream
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
info:
  artifactId: "@project.artifactId@"
  description: "@project.description@"
  version: "@project.version@"