jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email: false
script:
- mvn verify
after_success:
- chmod +x travis-docker.sh
- ./travis-docker.sh
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: NMYFu54H8udSkz8DRqugI2tCaWcCBoB61Ti9zeja1ENZcrcUyOHurT0GMh5r0u6puuwpyVTSTqorfoXE96zfBH3wQ+2E/d6MfiCWEFfo8Gj7PPCmtcygj2liudKMoMib1Zdt43uTQ8gQGH9LlJfPaNHb5ol9KEbmwu7EG9FF+Yvnl6EhiFzC5eYN2CfeASbDR4aT4c/dAiJM1jH0Jd0izBDmL+5XffszM0I7PNsTuSGWJFTX6nyWxQVEuMDtIv2INozEFZb+13D+b1BJhCyPbGZm7Ydf+aA+TkM7o5aLr0pLAULTj3UTnlTH2KbQQ0747t/tjWPwTYoYfQrD/uxeYsmKBeRdXeu0FR7wmsHXt/8SrFPCOduUmBgQEGgYdIW51HeREVVMtdQhCP5BRokuQ9e7TL13wkb6VXwm/uVVqKex7gCrPUgfNXKZfxCnCkFV9mYIzgaDflA10yyUtLSCsDbx4gbJNo+wjt7h8zddpdCrRLDwDii6OsqT/BFUnFPqig29C4x++FvnbdRDcF+gypZB0T/d05nqDMshNJ93XYuj2+Q9R5hEgF2jWjXBwd4nzHEYGNz/NhPPx4JGq/F7MztU5mKEvOpQd1ma7jRja6dCr/VIJWXPhFnDQLTPAWO7UIVXlESe2Pad5u4/ZX93jGofD4b2dV1h33VgVIidW4Y=
  - secure: 2qeH5N8eSHMOqTS67V9Yd6TmmMMorgrG95yMfpKUhFdi85/3QBj6jdJPDPrQjhyneSd2MVAABJtxCQ7oMm5rG3C8N0mpfktqgiZ7foN9PgM2OIcO2kzEG6Ik1ZdADtJuGeeohaMgpJ2PgD9SbgosOAIwn5PVY6tMrzrj2POkYroa1AUvxQbQqBbUK79GxehOtqa9EZ84h8ZHLrh9Lqfduwy5ZGqySEGynfd5EmNpjNKVE2YiQjuFYnfbmCXBJF6FGLf1zmTmRr5IS7+4oIkZDmW3yNILDYLLeAcABhPz2qiwYobr3PjRieUDJYYmyrPWRa72tST9MqIRj7l0AWD6AbCgtHbLpI0iZIclXTPhauR7woi53bFXFpiXXQEoAYqrzVLQ/8JnKKrUkime0HWsMgfNIYfFdu7cKwV7BhyltH/1i/KhbZGg6mEXMaOyg89qR/XBYqakeql98WC2zHa5JagxJ24t/5OaQdmpWnGuzi0a/OkQg+x4GdWcwLMMB7r2Bh2SOGKVQGd+wXmJUmbJMss1QaQ4l5z4CrIuJy6LVsRxdX33ZTLNAXQ51ctJpDY1GeOWLGlHH0Jo7ntctvVrv8sMGC6fSBHcgLXaWuITQPaZgAM6rMVNg8PzjyPyPre8zprnfHYHa0jENsooeNyzJAUSOE/+NZT6WLVyUWn0bxw=
deploy:
  provider: releases
  api_key: 
  file: target/triber-todo-overview-query-listener-${TRAVIS_TAG}.jar
  skip_cleanup: true
  on:
    repo: triberraar/triber-todo-overview-query-listener
    branch: develop
    tags: true
  api-key:
    secure: Y73BZEboAnKYjj7TgtRY12/JIRirF1GcEpv27qi33YNVUCVDDi4Rkt0rDStloYcXeW5X+ykM3iWpRRDDSo3ObKCoqbgs7kWmVg6Y3ql+ip1WnoIKBS4uOYOZaD4bwRP/dkrKjJ6jNkgrMlvD0LeVfeMVtFdEtm/ZFMccV9l05mCux1rUG8EPb+KwigAD+PX3VvAk7bjhHzy8gy0LIE8Xc0O8EnL5iUU1dOYQelqhR0MgqtptqWC8D6a88VgEzuwykaACWzmAZvtsLqg9WvLhzgi8v39TXpcTTsBeWqOu0cUp7FOn1gzSP5glBbWw7fpba17pvk+pwjxWPJ/ti6iyMgMJGzXDXZeeuYJjPYO1QiULW6pHoGogaAKcdFTr8qW3cwtvNEO2+6TaqI/g67hBCtZBfY9e/8ghUh8Rqs69kkxAeuJhvvB1yEiOQFJU40ufulAAqPqcPjR5lTgeJuRMIIaAxKUZHuJNV1ELiFGViTQtp1kO3KC8XZ1Ogd+Hy2Rj2JhL122IhoZGsSbOgAU7xTUoucbg7MoRwCgi0mg4VcAof1GsKLY195dS+ArJqlOXcghGE5VWd3+8whTcbNJRBl9oi0dtEkmJF87J7n6pRHKASMeoSJeoaB+IrobzQq7RRxDP19s5dKEmpwIOfXnvmKYkIV0nT6IuvcQJeLB6o4E=
