jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email: false
script:
- mvn verify
after_success:
- chmod +x travis-docker.sh
- ./travis-docker.sh
cache:
  directories:
  - $HOME/.m2
env:
  global:
  # docker stuff add by doing travis encrypt DOCKER_USER=<> --add and travis encrypt DOCKER_PASS=<> --add
  - secure: 0bA5TX7fXhac7AwIOnuJrIEtSzyToMuxlYYVQvQ9NJNvST6vxKQ1iJox21J/UQSy5c5eZ83Ix/C+byVz0MpVtIQmSjOzCkyXJGfDPcszEOJGJJM/Iy4etzWI+IhaVvbopJWpL8OKRRY+gMI4Z5pFDACi0Acgn9/B+/GdjVc96mLnv9+hpkftVdAxYeAAj4BbD9TAPGgOytzkRHC6HmMFONu0E67gSnFXgqeoTzdSvCHNIf4JNx90MhSbzik6OneRuiuLxyePhh0zQuOIjhkWwbswmGkbaz0yjxUGSFHhzXOK1LLuMp9crkSfj+6iEI3rhxfxc3H+lom6ahm5mm0Lh7ynA5EyLUrGhiPuybduBVqgtkace5HFjMcXnw9A12meSIFyCTpoxATnMOIbEPi9vxiu4V0LAnMYQuGgXW1fFuw6hAdVBaKGQzqvJSLg/ZoQVv2Yp6siHmiI8uTEdoN87o/7WCZEJ7nZ3+i9Seh1HDbPhFeVYA4KsD8lPF7y2mwWQ+Dgz56p/ICA1xPBSI8cacnIK4nmi5Q6LOFdl8I1jRLe2XCLiB1VJvO90J/UrXm8RM4tpxnp4PcrlXB3EuUeraEAeCJvuGS4OP/HBCxX9WYwZlAjDSRxd9nxqV1WP5RhFM/20FBdy0D8oYcNmZ21tW7N7zgxxyAqjoPUNWRzc0I=
  - secure: n4P3+8uc+mDhQG9/9lXxoa4PbFry6yAXiqfVYzW6lZ6DebsZh91su5steMgRJ7qcpf/iWVZYPPdNMVE6CqghBzJdSSEDZhBmsLHNYONBrazhG6YSBUJcW2g98IQkrmpdBvC23a7vzj4vfUNEgiLQ71kDpG/eix7rD+aCMCtG9ZQ9FNu+wSlm3hSKFvuasPfk6BHfhrsMmpvsfH5sPGTXUPijFfkLbw4r4uqcKhTZ96YinriSOSoiQZbhZwV8CRCRR/w4dCxLXI1w7xPID5S3nzMLcJ4qs/wJ5dqsRUbWCo7MD0ZUdklWSDJh6y+C/vA289ZpDmiDaoyjo2PqpmRKE4FHZxhnIbociSMPWU8Pqew9MBccDHLhBEwUlC2bjGhr2B8CVvgXxZxTsO2kyspr12TDhWSjG/H5kxVcHbzcZmar+pdB80wsA1mEDca6h9VY6//+E5vLxTeFdw1fgEOmHWrsUTOVCKBGNjVxhVQya/PboiWymi7BCU54QvNPFF6Ue/rHu6sNQEAt4/HwXurMiJRYBEGd+PRqz3X9qEzcnF92Qx4PMST5zvQX70La5+Gn3ZbvY/c6pUENhJb6++nOD5GpY0/sWdlfyFj3UIUwQVEoWX+v1s3teuufb3ObPexv1e+qzEhfSHwkzwikpQm1y0VDAATnzmmxG++VhQrKvWo=
  - secure: ayA8rD8l2FrWOBDuT6D58EDHk1ptOIPpglOuaGl/d6jkgc7q/4q5OO2OOYaCTrQ4QfRmRq09a+pLiE4am0x+BhERMT54W8Rln4DJe0Y//NxjoqkzKlDWjRIoLKFPPigU7jtxBWNiWfsvJvUzTH+WdHM6MJhHgFoHOfcLkmijuXy68+GSFYeslQYnmyD46v33bmJn8768+DXnZcKo7NDgOYWoKwTdqruVMKbN2z3PtvsiF02+1LpoAEChM3LB1JMwxZTUTgxLvmHmyMHpgBHlXDyljxaWDFlN2nuyzSSPvgrWofAx3769J0u0gjuksKI6AuKGVAb/NersCGjY20i4T/PtVnykkXOlT/LKjSSXD4xq7ejV6tZo9058kLO6QZB9xEXKPZucq8uWcwDj7rc88h3xeHAeofJqq0EbUBcNprjHS/dcNmAAiZ7rJSTZRjKXMxApI3vu2dHUrk/iWNp6Tfldmj0iORy4yw2wRiP97QBfFGNF5YBGJxDsLrLT2FbfrbGkYu0Ybb72y3qn7Os9e3FS5dRmk7xnuUzPdUJJnOlAhyrWLiP6U3UoRxz9+bL9MMgw364KScWEDpukFVxm4W9fww1qsEe7bVWt9z9cq/T3y6JAsHY8RFV55ddeb2aH+itj/z/g4b3MytZi5hX1l7qB4LvIgs7aA31R5+nbwNs=
  - secure: LZLsVc4BiaBF7/OU2KixmvtIlX0dLhv2WXN9VvLoFouHUeOTSFIV43C36ZMBv/DatAFx8AXCKE4sYH1KqpTzWAzjFU3p5tvSMrJemA3yOZDcdgFpH5V+YFh7OAY+XW3CRQF04uYNN+5YCrBOIw/xH+WXupiQ9gU8HSz3Yeg6YlPSP5Pg5HVsCMejtFWx2EVzwX4uIBYIX5tExdWxHrr7It44ShZKa4fxhDVsdD2YXbr2WFGm7I3w/QiN7oP0/k2kp4DHSdX0oBGD/sVtaHjdyAq6jstdXe9fP3+Qs98/3abQ+bsbhLj3Wmy6zPrPUxh8VvWU2Mf37Uo00VoxkD8pNhIWAhpdnhPXrpZd+E6KunjxJrjdqR1GlR6IqnbaMbOBKujplXLt1brnO2ULcTzaCr9YLYHnCSPI/E1sL+aCq19ffgJhizrqbZ7jSzOGy9A4AEwLg4faLSEdd2o50xJ+0XI5hkupcp7jgtBHTVeoe14WKCPN0Xq9nMcW/xOTadal3r0UlvhDTvecvhwMcps1SLCPuxw3hPuNfC+JVu9Vw+7YI8nCDaTUUUwoHBp1iY2zlpS2E/6GuePloumu3jZkpCYSklUuV7fsfv97eBoa8Yw1H7sakcFMQnOze24Hv/m+WTmmxti6Sos2cfh+QL/XDANgdxF8XTDmDLwjb5f6gVs=
deploy:
  provider: releases
  api_key: 
  file: target/triber-todo-hystrix-${TRAVIS_TAG}.jar
  skip_cleanup: true
  on:
    repo: triberraar/triber-todo-hystrix
    branch: develop
    tags: true
  api-key:
  # generate by doing travis encrypt <key from github> --add deploy.api-key
    secure: iOJzeZDS31Gk/LhOAiGDHeBzVhwcKg0ai3p13WT1p+YDz2Rmx3PrDG0JSjXjWaFIZp6EkqcioFS4zagdJhQNRESbYGiWUyC2W6UJOCQbHN96AGR5bN4teAeB3N9fH4qgUrUepKMsBg5xy2zAgeJmwY0KICBb9FKl8ikLfjwaUvEaE/c4bgjXhF7eH83tK/xsnmzhbLQKYMpW01+amvpOEtOZOs/JftpwtA0ii2sXzKXAEYIMh7xocvHJaFTbQdAhhsgXuK7yK/cpSkBsy0Vj7nlAgU63UCKFvzUnqxwAlN5LIvl12PGmyFXyMPupBfI+Jt4fLYwrMam2h9Q3OHX/ktuYeqacr2FVMBCAf8zXHCf2MCtMPxuX3HAT8DWJC5aPC313roxwXNrlY5r80mS9wvRa3nQSlT13OgguNqbqGeGsmydEcMu02TfIfarD2mb84KdiT/QyA5FXusW6Pw64u8nb8EQL1WmiO7D8gN8sAFLWIX/rhVQl9AsJiYMv/effX3rV/3f1djntWuYZtDBoBonxNMU4/V2wZkdkyIbYAgoowLL/MwtnXdQaCoQMTixoDpSGeLUzN9gJZKLx75GfK5t7DjftuwYUmYTUrzr9/nGu+Ef/tGFZlwVX9xqkBcpDqG0O04KYzpoo7p66hVNOugdlaUlyIHChab7KIVrhECQ=
