jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email: false
script:
- mvn verify
after_success:
- chmod +x travis-docker.sh
- ./travis-docker.sh
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: dyA1rTcu1vSSO7ggsRX/MYX5ZzFY+Bzj8cYz+snk+XsWW5D4ZT89YLlTZbSta+7OHBPoalSmZjjcAKna3C9OESC0sGbLK+zDglX1i1I3X9QBhiGIp1r0Rp1nhTZ7OoKgPhbjvkMp8NfmfmRS/hJYDVJlBlppYbQZzcU3LQG+BUSr4//8F93zmhr7JUBrW58xe8EvVSLt2KpgpBd4wpExM7qHOzwhIBzXFlTKXL33XbcrorHFqzGujB0Lnu44OgOX3a0INKOjV5zY9NLw5Afns1zpDD4YzOxYgfrOHPDu0bfM9QwMhd0bL9jt5F7bow0svQ7asXhSjc8GjtaBQVRkwNEzpxPuUyCWM11eBG2z1OxO821avr4yieGQTtCTfRsPEYG9wpIEC0IHBYEyNQgvkL8VQ8oaCGhUDB/+mi29Q/JakuWV0+ChQcnizYPA081KPB54lmJ4tm3obkDxuMHoUO1OfM5RQaLGOQ7JpgqJHqE0Tc9oLf2WI99V6luD4uNubAoMZ4uz+hUdIE0w7LqQOsBE+gFoqVssCHF5usOGszzY50w4XXKjREyog2P25KBUzzHD6GSIkmI8dSXYGEod2IG484CDGQ59oHEBvmXocE2iYXCtDjdO38fN/P81ZZWOQ8C3/BME+2HMs9XvgwygDpjS3H6xHC0AfdAe1VFuQyQ=
  - secure: J308U+aWxbTV1QSfdPTCzEiYSL30mMCoyQP8Ae/3ZraKWg8FSzzW4ATU2ibtzqL8n0TkKvzhX7pMY4LE1hh1yLKiH/vvy15tMAgFQYcJKBpy9reX9rlGqRFitw2rb3T4MU/OWEQLNpZ4MW4XQLuMvC4YZ7myq2zt+bEbCw+VhEw1hyoFrDsuy/pBDko0ovISTaYk9MmK2PHjOKtsFIFsvDwLEvAy0LKv8hwpjIuPvrBBvpSFGjse2jX1kjHbj4pYipmxofA4dAC/NUYMYS1Sj4iM3lRRxjybYx+IEd+WcIMIu6lkwrAzhj7lQaxboXohnadh0GA3bQM9MZGq9b+BDE68GVlUXMzs8idlX6Qyc4MUF7EsYB/8N4mCtta/tKbTeKyO7u2WUN5gJVH3fHx3u1kzxn9aCgDT27/u9gUoADDJ44Giq4FsXJEUSNmgi+dXOiQhYiuXjQzmoSA1N8kF50VS71HoSj7GFze7nQ0jWBs46n1HkJc33RAu5eA0Vn1ntWR2mLW0Z3zP5n4IUcS83QLqEiJEhIYvQYWntG21FRMLs5Yh/Fo7B8PcBiiNAoXWQUuwEUyRr3yFAMkMI9HdJ8tw3tn/Ekn3ysiNLKb2sJEgWnAYngRZ2tp0Y3hWzS5GNZUIeZi0GbhmcUKTpqWOTkBbtlVmzcrN7g7AMw+PvYA=
deploy:
  provider: releases
  api_key: 
  file: target/triber-todo-overview-query-endpoint-${TRAVIS_TAG}.jar
  skip_cleanup: true
  on:
    repo: triberraar/triber-todo-overview-query-endpoint
    branch: develop
    tags: true
  api-key:
    secure: HD2A3jrgL9pWOMiPHrJqwZkPP67vshIXLtSpF4o3Wfz2NZ1Q3ya5tboz0LtV9WQeBH/VOc4tzegjNoZKYtk+YUiMzhdsgfQj9x6L2rYOg4lnWKAfUFnRGjuGYIHvUfGAKbPasTXnXap2Bn0VINsXyqT3/vYQE01cKWk0eEiQjvKuj2DSFgh0WlV5vaOXVgwBCeiBfIlu8cgCsdzsQvSQgikRXQjWe9FNtoGUDmqCmg/Qa9BVJYZe+P2zRltRLmOvPHAIo8q8DigVbHWmyp6JSTYHPcOnq8f3BX6g5GrbkpJ18ADiysdcbK58RBT51c5jIL25E0+0QHT51kPruvPnUO3YW7JoGMB1PLrS2L2vH1bcF5CMqGLOMAo5pBT7CZwrb/X7Nc4bTSzy0ZPzxvYiONRE8Oih3iJijmVBMGN5VfnLq/8m0aaPkmBzIDVxi9k2doU5Uw2klMAjbIKn91lk5sQ5nUPM/3V+4cpGNn++KK8AMzZh+tlomsiW0yLcEkKGmpj/UET0HaqwgvnusfPx0+14MkJCP6WekZKP3EuRZ2CU//+rTvW0I6rvCpb9AN9jvs1FqI4Ik0Ixf9FmPXxu59yjRuLvMp6sXEa7y+Fj9TiTYfLQYLE1LbqNQ10OoMjXoDwFhHzFqqyRiM/H2x7ne2ua26/DNhhS7te/3fzX/y4=
