server:
  port: 0
spring:
  data:
    mongodb:
      database: event
  cloud:
    stream:
      bindings:
        event:
          destination: event.exchange
          contentType: application/json
          group: event-store
      rabbit:
        bindings:
          event:
            consumer:
              durableSubscription: true
  jackson:
      serialization:
        write-dates-as-timestamps: false

info:
  artifactId: "@project.artifactId@"
  description: "@project.description@"
  version: "@project.version@"
