jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email: false
script:
- mvn verify
after_success:
- chmod +x travis-docker.sh
- ./travis-docker.sh
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: C4Widi4aXXbLE7bLdFuMOkGg6KyQsaMkEug5m6JID5NMNJ/MHph1W2nZ/ha0gMecWG+PxEwCXArT3pmaZ+v8lLZTlJzAJKq2wVeR25ZxpthnTcax2Zwq3WKVuTiP6+Nke8Fks2pgB9+nxai/G4KgpedXkAUTN4Tj1SBab00CwuZ0A6zghPC/xl/1fLJQcIQyj4vrOkajPMDQm89D8x5H92NAeRr7Ib5y5IKggTKOpH6uo05qAH2hw832jYimq5H1m9RwIL3qywl7004gylaTcv0H7BFzPb3yj7E3ZAUqJgvNAZlztLo6xJkGbc4EjeRUIZ7mmbrXJEEjl84i+cgBmHmp6jY85oPWwUX2YJUTX1wn61orNoxjq+OCMEK9grRTNXv1qDsNwRb1FsDx1Rvx7em6MlzcV7Tt8OnOkqilNiLhJPlLg8GBeYkkUuzhI8S2g7DbL3C26zf1m5rquZQ2EZiRnNgSSVJSkzHxUao3sm/BJBRvP0D6MElJKc/6C/dHS9Y45hbtkZqnKqeWsFVkr13DdN+I7c/3dhLuV7pwQ3AM44dL6JKYZ0DMZdUUaCiCjfpWqFam+mHLAVtPkyPk/fmkO4YE7las7ACQW0tgP6XLjdy66jkZtMHIUI0+wJtH7M3sWtEogPhryBnw0Kt3vuNKvnMI4mrtrkDOmCGJ6os=
  - secure: lMKPVJhYn1mIz7308k3vG8L4wKctX3l//BcaTCPTtFZxZkb0O70+2T7D3FBXxbKuZj9NO7xlW8LlHxANQdRcDa9g01Jsf9dhDcIn5BLaEuzXPCXqumeSNcHbb0h9oSxgiPGYXHBCA0+G/UIhuUjY8uUPXHErI2D0n+srD8w+9hiXtbfedjWcokXvT9hJA7GdZhuMDUZJcmhsZ4mYYcPOym/jknZXYhBU25q/4sIxiHWohOQN/+2+V60JeS9xNN6+EbVc/XrnC4Vz8gORYVMK0zjbGQ0A6Hagx7DgzC3odOAMqRtHaEhCDg0+NzCxZssaRUHKn3LHIouF23oWC9i3Zv1vYsIJpYHxEgkUBG6kiFGh3TfUlL/a3RW1OsarI2B1K3i1vV3iK8E3l0AixhxG/V2088t5wDfasNX0EnXE7MyDdmAZqtPhtR+97ELX2kPHyTvCJ7eUMRohPLZWuyL7aBrdaZWDUbp1Y4KM+WRdYPhTHMy2YsPvZH1kZv/j34tTLSxyL4ZW2p6Mb74QGL3WXVChLUYkGdqfukkZsXn3rl8TGRTDsTtnoiNF8rjuzsICCcUMCahyldInbMQSiPvuNKrCe99XcJKQOWB5WIOlE9AqnuHKeO/mPPLQYhU/30N2O/fDA1JL7wm3vWkP6LhL3mt5m3nKYcZP6FuQFcpzAd0=
deploy:
  provider: releases
  file: target/triber-todo-event-store-${TRAVIS_TAG}.jar
  skip_cleanup: true
  on:
    repo: triberraar/triber-todo-event-store
    branch: develop
    tags: true
  api-key:
    secure: qbPCym+yA/WVdSeXi2n6E17EvieNGZXAyc8vTZ/BKYuJTPZv4B2KnkmegJdccs3c9dvhSbeduoehZuc6y+gAAOLPPH9NAOSGcipBQl1EPUTatjG3kF3KYKe0uJau2fuHE8sWfVWoF4OcC2fMu0I1kcEJ4GxAuF2d3n2TTEYHTLfOIHvLlmzNxi2vUwXYkv/bXP4yLQPM/FVbxNWKcjvY25J6DLngVCsLlvzHkGMrfTvaiEK0fD1Fo3JF0uOai9rjTA7XkZ/Nfvi6vB4toiaa47hQhGwlwsTRAZT5idPM/CsGwiCTQUk+dG93/6thhmBYIZ/ceH8AjOHLPBj02lDzPwrbWvmk0Vvf5HLD9y2BtaMqgU6oLyLP0pkIYKSUIGfTU0IQsV25hFz3+PfisKlQILgY814gZDviQy0eWlTxyhW7ycaDQiDQaZmZVcsh8FN2bdysiNPrtrkJy0UyJP0rv65KbczLUGqm46L0NxXGvRz2YNNlwIP17luQodA9A3LsWGW6Sfxo45/gejI3H4lGUWSggWPhamMxZvWc51PqjaKs15bK8h2j8qmxXdlg9gy+XJ4+QvhqZbCZ9FESzQLeayABbo8lRHOWCmmpGoaNeAYOtdAFkFNvbgL8FxQnOcTLPUX48/DvzjMUN/P2JsDpJsr+YwAkzYFDjsvqx/nzpC4=
