jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email: false
script:
- mvn verify
after_success:
- chmod +x travis-docker.sh
- ./travis-docker.sh
cache:
  directories:
  - $HOME/.m2
cache:
  directories:
  - $HOME/.m2
env:
  global:
  # docker stuff add by doing travis encrypt DOCKER_USER=<> --add and travis encrypt DOCKER_PASS=<> --add
  - secure: 0bA5TX7fXhac7AwIOnuJrIEtSzyToMuxlYYVQvQ9NJNvST6vxKQ1iJox21J/UQSy5c5eZ83Ix/C+byVz0MpVtIQmSjOzCkyXJGfDPcszEOJGJJM/Iy4etzWI+IhaVvbopJWpL8OKRRY+gMI4Z5pFDACi0Acgn9/B+/GdjVc96mLnv9+hpkftVdAxYeAAj4BbD9TAPGgOytzkRHC6HmMFONu0E67gSnFXgqeoTzdSvCHNIf4JNx90MhSbzik6OneRuiuLxyePhh0zQuOIjhkWwbswmGkbaz0yjxUGSFHhzXOK1LLuMp9crkSfj+6iEI3rhxfxc3H+lom6ahm5mm0Lh7ynA5EyLUrGhiPuybduBVqgtkace5HFjMcXnw9A12meSIFyCTpoxATnMOIbEPi9vxiu4V0LAnMYQuGgXW1fFuw6hAdVBaKGQzqvJSLg/ZoQVv2Yp6siHmiI8uTEdoN87o/7WCZEJ7nZ3+i9Seh1HDbPhFeVYA4KsD8lPF7y2mwWQ+Dgz56p/ICA1xPBSI8cacnIK4nmi5Q6LOFdl8I1jRLe2XCLiB1VJvO90J/UrXm8RM4tpxnp4PcrlXB3EuUeraEAeCJvuGS4OP/HBCxX9WYwZlAjDSRxd9nxqV1WP5RhFM/20FBdy0D8oYcNmZ21tW7N7zgxxyAqjoPUNWRzc0I=
  - secure: n4P3+8uc+mDhQG9/9lXxoa4PbFry6yAXiqfVYzW6lZ6DebsZh91su5steMgRJ7qcpf/iWVZYPPdNMVE6CqghBzJdSSEDZhBmsLHNYONBrazhG6YSBUJcW2g98IQkrmpdBvC23a7vzj4vfUNEgiLQ71kDpG/eix7rD+aCMCtG9ZQ9FNu+wSlm3hSKFvuasPfk6BHfhrsMmpvsfH5sPGTXUPijFfkLbw4r4uqcKhTZ96YinriSOSoiQZbhZwV8CRCRR/w4dCxLXI1w7xPID5S3nzMLcJ4qs/wJ5dqsRUbWCo7MD0ZUdklWSDJh6y+C/vA289ZpDmiDaoyjo2PqpmRKE4FHZxhnIbociSMPWU8Pqew9MBccDHLhBEwUlC2bjGhr2B8CVvgXxZxTsO2kyspr12TDhWSjG/H5kxVcHbzcZmar+pdB80wsA1mEDca6h9VY6//+E5vLxTeFdw1fgEOmHWrsUTOVCKBGNjVxhVQya/PboiWymi7BCU54QvNPFF6Ue/rHu6sNQEAt4/HwXurMiJRYBEGd+PRqz3X9qEzcnF92Qx4PMST5zvQX70La5+Gn3ZbvY/c6pUENhJb6++nOD5GpY0/sWdlfyFj3UIUwQVEoWX+v1s3teuufb3ObPexv1e+qzEhfSHwkzwikpQm1y0VDAATnzmmxG++VhQrKvWo=
  - secure: QPdwQUuYeQSwKPG7iycz+sLQiQCTPUngpa0qunaC389DQV19wzo4Bn7lEf2AZLlKqdiggFDheZboytL/zsHJwNIKZWuJNspQ62sbdYteng/NvciUa6hdKJDmrNDY07KXyvJ7+xO9AkibY0GsF6f2dIQcZyvdRW8kswzTKqjuo/FzMPIBQQhtyNgSZJSlDJLp1MjUe6mt/bFrcOICWMnBpd6QdZ6fxDAiBosB+aUJpEqrTDWwjn4Wc/079aVcSiU1hvyXcmJxLnSECltmFj88q7eDOPPnjmpUj76dqzShqLz15nrVwiEff2aV9NMpw8xt90T3mJB9xrOmZlejb212M1lWszYCOCjH8pjs0qXyLPAXtopwOM3R8QxOWoFCYZcmKoMuX/GoESnRmpCd8Vjh599zZ5dVIMEryukdlH9QAg9HxlMjSm66W9VSExDGa47G82Na4IptH4CJI4H12Vs/IopsfohsJrboJ+3jFlkMJZV2lYoSStppb2adSIAI4jvOE0x0RTe69c0ge7k6GWN1hb1oSlfHlvtsJQmfnVv5OYgTOyaTzt5WmecVbWoNBDhoHJ1G4tBzj1w8SpamC/h9C3Z4sCL4X6Y13LbNi4gm5BBrP9ugxVzJGqBzcBvxVDU3SLhOFHcPtCJj2pwx8Kky/uEbbldbqOJBUlw9rG2JotA=
  - secure: ULBTKDKFTOxR6cw3NE5Mvai0h0x1O5dxHLaeiNzhPacuJDtt6j/4h1KnYwwW+si6mQ2zH3HF3onp2VLriWrHeQAL/9gxr56IxN1jfvDK3s+bGhaDuvBMjEWAV7TN1TvnFsT5wDHLMS/mm3TZ2z6tc6wO6urQidrhU8M/modFHQvlJ+priamNTieNO6yGiKLEPP55xIsOxipHJeB7oQjfaMhOx/9EqbIvCvcYuIprc5LWZS0xzzFUu3waZLhptWppGpQoAK2r6W+kVVxKWywf70elcOe99+VHh29Z4Jv+NKUWBGi2NelRQHwZ9NBs7lteuOpHrEX6NlsGJi8H+bKIMyLfnGfhCh2v+l5I4a16fC+s1cDC7E0XacA3hxhlq7ciRUEHp4c2nPlW9PF6NUjhFtIX8v0DmAj95P48FX0J5Dl+g4tWQcIjjcziLtw8XsWwyoKOSfhqBsAmj8KWpcvxW7yaYwGXFI/hwqiD2NXkGnYXQdQyX8H1vHHGoAPWjJuExD2neC23fgjtVIYs32CiSB/SZYrEqvmA5A/NAe6dFCXWYL6CMEBcS559P+1lzaSfocJcRab/HMdDyAliQ8SXqRC+76rk13tXcp/gc1h4fx7jPEaoGRiqgn97Fk4zLlGNfsodzDLJD1cFThgzI5CupqtxmpqfHWWd4z5SLa5olfw=
deploy:
  provider: releases
  file: target/triber-todo-discovery-${TRAVIS_TAG}.jar
  skip_cleanup: true
  on:
    repo: triberraar/triber-todo-discovery
    branch: develop
    tags: true
  api-key:
  # generate by doing travis encrypt <key from github> --add deploy.api-key
    secure: t2W4EVRiyx2GTDAluoMEHZdtJvp9IOwVID5TS7LDnr7dj2yPp1LUUmqvn2ggV4ZnNWQuQ3tldm205LAM+Crc8muYyfIxUV9u++AvnGaw888FL07yYXXojMarK7lFxtk5uUp6b6sy/MyhSq3UY9Hvj+dGCh9UVqi0tC1uWiJHav+/6dyXqHsiKMiNQTaSW6IdbXGbXRvrOzXV759dXxzRXfE8ny51BGKgr2wrr/QFtgV8theSeNub4b9PyL0rvPo7CkbjHHHtyzu2N0WbCaj2z9LLLTodAjQxx4hXBfELmANTe29JA4Q2v4SA7Vd6hcOKUoBwEFDB9tP/kc0hhQ2WW1B36mJH7RpcjQxL5BaOXrF6BeUHTBxcx31B8J/eaOOxVRMbeIr59Bn3CM79cpSIpDVKr8pVOMW9Kt/EIuLv0IH/JNsToB7TYEHf4DKlaUwYyaIfq9Vj1CrF4cLf0CnE4K6wDNspghlEgszu1HLBKTc88N3ZyUQfHU3i3PDNoYVJQXy/EmR/rTuht3WkhAuHfjtwxdmfg/w2tN1Cqa+AnF6dqXbQyQ9x0P2DzzMy0p4UAIL51mW6F9Xax7KvThN7Nw1McEG0P1PCnYXObjtpYacX0g1yHi4kb+s3dLjIo9APk31YLpDHjwgcKm/UTHOPndSITyI1Qt13pP7kVKVU4WA=
