server:
  port: 8888
spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/triberraar/triber-todo-config
eureka:
  client:
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

endpoints:
  restart:
    enabled: true

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

info:
  artifactId: "@project.artifactId@"
  description: "@project.description@"
  version: "@project.version@"
---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://triber-todo-discovery:8761/eureka/